<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LumexUI" Version="2.3.4" />
      <PackageReference Include="Supabase" Version="1.1.1" />
      <PackageReference Include="TailwindMerge.NET" Version="1.3.0" />
    </ItemGroup>

</Project>
